-- Insert seed mantra data
INSERT INTO mantras (slug, sanskrit, devanagari, transliteration, meaning, suggested_rounds, emotions) VALUES
('mahamrityunjaya', 
 'Om Tryambakam Yajamahe Sugandhim Pushtivardhanam Urvarukamiva Bandhanan Mrityor Mukshiya Maamritat',
 'ॐ त्र्यम्बकं यजामहे सुगन्धिं पुष्टिवर्धनम् उर्वारुकमिव बन्धनान् मृत्योर्मुक्षीय मामृतात्',
 'Om Tryambakam Yajamahe Sugandhim Pushtivardhanam Urvarukamiva Bandhanan Mrityor Mukshiya Maamritat',
 'Healing, protection; removes fear and grants longevity',
 9,
 ARRAY['ANXIETY']),

('gayatri',
 'Om Bhur Bhuvaḥ Swaḥ Tat-savitur Vareṇyaṃ Bhargo Devasya Dhīmahi Dhiyo Yonaḥ Prachodayāt',
 'ॐ भूर् भुवः स्वः तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि धियो यो नः प्रचोदयात्',
 'Om Bhur Bhuvah Svah Tat-savitur Varenyam Bhargo Devasya Dhimahi Dhiyo Yonah Prachodayat',
 'Awakens inner light and clarity; dispels mental fog',
 9,
 ARRAY['STRESS']),

('om-namah-shivaya',
 'Om Namah Shivaya',
 'ॐ नमः शिवाय',
 'Om Namah Shivaya',
 'Surrendering ego; calming the fire within',
 27,
 ARRAY['ANGER']),

('so-ham',
 'So Ham',
 'सो ऽहम्',
 'So Ham',
 'Breath-anchoring "I am That"; grounding and centering',
 30,
 ARRAY['GROUNDING']),

('om-mani-padme-hum',
 'Om Mani Padme Hum',
 'ॐ मणि पद्मे हूँ',
 'Om Mani Padme Hum',
 'Compassion and ease of sorrow; Tibetan Buddhist mantra',
 21,
 ARRAY['SADNESS']),

('ganesh-mantra',
 'Om Gam Ganapataye Namaha',
 'ॐ गं गणपतये नमः',
 'Om Gam Ganapataye Namaha',
 'Remover of obstacles; new beginnings and confidence',
 9,
 ARRAY['CONFIDENCE']),

('om-shanti',
 'Om Shanti Shanti Shanti',
 'ॐ शान्तिः शान्तिः शान्तिः',
 'Om Shanti Shanti Shanti',
 'Invokes peace in body, mind, and spirit',
 9,
 ARRAY['PEACE']),

('lokah-samastah',
 'Lokah Samastah Sukhino Bhavantu',
 'लोकाः समस्ताः सुखिनो भवन्तु',
 'Lokah Samastah Sukhino Bhavantu',
 'May all beings everywhere be happy and free',
 7,
 ARRAY['GRATITUDE']),

('saraswati-mantra',
 'Om Aim Saraswatyai Namah',
 'ॐ ऐं सरस्वत्यै नमः',
 'Om Aim Saraswatyai Namah',
 'Clarity and learning; goddess of wisdom',
 21,
 ARRAY['FOCUS']),

('aham-brahmasmi',
 'Aham Brahmasmi',
 'अहं ब्रह्मास्मि',
 'Aham Brahmasmi',
 'Non-dual realization; release identification with ego',
 21,
 ARRAY['LETTING_GO']);
